### ISSUE TITLE
Erro ao carregar xml de nfce

### ISSUE THREAD

**Issue by abadvincula** [Samuel-Oliveira/Java_Danfe#13]
está dando um erro ao carregar a xml da nfce, possivel mente erro na compilação do jasper.

net.sf.jasperreports.engine.JRException: Error loading object from InputStream.
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:230)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:210)
	at br.com.swconsultoria.impressao.util.JasperResourceLoader.loadJasperFile(JasperResourceLoader.java:44)
	at br.com.swconsultoria.impressao.util.ImpressaoUtil.impressaoPadraoNFCe(ImpressaoUtil.java:100)
	at br.com.abatech.agropet.util.Impressora.imprimirNFCe(Impressora.java:1156)
	at br.com.abatech.agropet.visoes.jdDocumentosFiscaisEmitidos.lambda$jbtImprimirActionPerformed$2(jdDocumentosFiscaisEmitidos.java:453)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.StreamCorruptedException: invalid stream header: EFBFBDEF
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:866)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)
	at net.sf.jasperreports.engine.util.ContextClassLoaderObjectInputStream.<init>(ContextClassLoaderObjectInputStream.java:56)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:225)
	... 6 more
Exception in thread "Thread-26" java.lang.NullPointerException
	at net.sf.jasperreports.engine.fill.JRFiller.createReportFiller(JRFiller.java:267)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:156)
	at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:145)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:758)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:1074)
	at br.com.swconsultoria.impressao.service.ImpressaoService.geraImpressao(ImpressaoService.java:84)
	at br.com.swconsultoria.impressao.service.ImpressaoService.impressaoPreview(ImpressaoService.java:76)
	at br.com.abatech.agropet.util.Impressora.imprimirNFCe(Impressora.java:1158)
	at br.com.abatech.agropet.visoes.jdDocumentosFiscaisEmitidos.lambda$jbtImprimirActionPerformed$2(jdDocumentosFiscaisEmitidos.java:453)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Samuel-Oliveira** [comment]
Corrigido versao 1.6
