### ISSUE TITLE
NullPointerException ao Tentar Gerar Danfe na v1.2

### ISSUE THREAD

**Issue by glaydsongmv** [Samuel-Oliveira/Java_Danfe#5]
Olá, após atualizar para a v1.2 quando se tenta criar um arquivo PDF seguindo os mesmos passos do tutorial da página https://github.com/Samuel-Oliveira/Java_Danfe/wiki/01-:-Impress%C3%A3o-PDF-Arquivo ocorre um **NullPointerException**, segue o Trace:

java.lang.NullPointerException
	at java.base/java.io.ObjectInputStream$PeekInputStream.read(ObjectInputStream.java:2887)
	at java.base/java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2903)
	at java.base/java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:3400)
	at java.base/java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:936)
	at java.base/java.io.ObjectInputStream.<init>(ObjectInputStream.java:379)
	at net.sf.jasperreports.engine.util.ContextClassLoaderObjectInputStream.<init>(ContextClassLoaderObjectInputStream.java:56)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:277)
	at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:262)
	at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:737)
	at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:1061)
	at br.com.swconsultoria.impressao.service.ImpressaoService.geraImpressao(ImpressaoService.java:82)
	at br.com.swconsultoria.impressao.service.ImpressaoService.impressaoPdfArquivo(ImpressaoService.java:32)

O mesmo ocorre gerando HTML ou tentando exibir na tela. Tentei criando com um projeto do zero e mesmo assim o erro persiste, identifiquei que é nessa classe e método no _return_ que o problema ocorre:

![image](https://user-images.githubusercontent.com/38701263/208515026-0bb2f6ca-ed86-4364-8e23-bfea95ee4b7e.png)

**_Utilizando Spring Boot 2.7.6 com Java 11 (Eclipse Adoptium jdk-11.0.15.10-hotspot)_**

**Comment by jonasricardo** [comment]
mesmo problema aqui para todos os métodos de impressão da ImpressaoService.
testei com java8 e também ocorre o erro.

**Comment by jonasricardo** [comment]
verifiquei que na versão 1.2 não há o arquivo nfe.jasper dentro do jar da lib

**Comment by Samuel-Oliveira** [comment]
Resolvido
